version: "3.9"

services:
  database:
    image: postgres:17
    env_file:
      - .env
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  django:
    build: ./backend/
    container_name: django
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - database
    volumes:
      - ./backend/backend:/app/backend  
      - ./backend/manage.py:/app/manage.py
      - ./backend/pyproject.toml:/app/pyproject.toml
      - ./backend/uv.lock:/app/uv.loc
    environment:
      DB_HOST: database
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  pgdata:
