version: "3.9"

services:
  database:
    image: postgres:17
    env_file:
      - .env
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  django:
    build: ./backend/
    container_name: django
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - database
    environment:
      DB_HOST: database

  frontend:
    build: ./frontend
    container_name: fronend
    volumes:
      - ./frontend/dist:/app/dist

  nginx:
    image: nginx:1.29
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    depends_on:
      - django
      - frontend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/data/html


volumes:
  pgdata:
